# Generated by Django 3.2.9 on 2021-11-19 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(default=1, unique=True)),
                ('item_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.IntegerField(default=1, unique=True)),
                ('move_type_id', models.IntegerField(default=1)),
                ('move_base_power', models.IntegerField(default=0)),
                ('move_accuracy', models.IntegerField(default=100)),
                ('move_damage_class', models.IntegerField(default=1)),
                ('move_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField(default=1)),
                ('species_name', models.CharField(max_length=100)),
                ('species_form_name', models.CharField(max_length=100)),
                ('species_type_1', models.IntegerField(default=1)),
                ('species_type_2', models.IntegerField(default=1)),
                ('species_ability_1', models.IntegerField(default=1)),
                ('species_ability_2', models.IntegerField(default=1)),
                ('species_ability_3', models.IntegerField(default=1)),
                ('learnset', models.ManyToManyField(to='viz.Move')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Genderless')], default='M', max_length=1)),
                ('held_item', models.ManyToManyField(to='viz.Item')),
                ('move_1', models.ManyToManyField(related_name='_viz_teammon_move_1_+', to='viz.Move')),
                ('move_2', models.ManyToManyField(related_name='_viz_teammon_move_2_+', to='viz.Move')),
                ('move_3', models.ManyToManyField(related_name='_viz_teammon_move_3_+', to='viz.Move')),
                ('move_4', models.ManyToManyField(related_name='_viz_teammon_move_4_+', to='viz.Move')),
                ('species', models.ManyToManyField(to='viz.Species')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viz.teammon')),
                ('pos_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viz.teammon')),
                ('pos_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viz.teammon')),
                ('pos_4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viz.teammon')),
                ('pos_5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viz.teammon')),
                ('pos_6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='viz.teammon')),
            ],
        ),
    ]
