# Generated by Django 3.2.9 on 2021-11-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='move',
            name='move_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
