# Generated by Django 3.2.9 on 2021-11-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0002_auto_20211118_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='move_pp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='move',
            name='move_priority',
            field=models.IntegerField(default=0),
        ),
    ]
