# Generated by Django 3.2.9 on 2021-11-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0003_auto_20211118_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_ability_2',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_ability_3',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_form_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_type_2',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
