# Generated by Django 3.2.9 on 2021-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0004_auto_20211128_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_ability_2',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_ability_3',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_type_2',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
