# Generated by Django 3.2.9 on 2021-11-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0005_auto_20211128_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_name',
            field=models.CharField(max_length=100),
        ),
    ]
