# Generated by Django 3.2.9 on 2021-12-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0008_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_gender_ratio',
            field=models.IntegerField(default=1),
        ),
    ]
